server:
  port: 8083
spring:
  application:
    name: '@project.artifactId@'
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: transactions
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  profiles:
    active: dev,doc
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: config-user
      password: ${ConfigServerSecret}
      fail-fast: true