services:
  port: ${SERV_PORT:8080}
  context: ${SERV_CONTEXT:/}
  bussines:
    agencyNumber: 710
  connection:
    database:
      name: ${DB_DATABASE}
      host: ${DB_HOST}
      user: ${DB_USER}
      psw : ${DB_PSW}
  security:
    ssl:
      enable:   ${SSL_ENABLE:false}
      type:     ${SSL_TYPE:PKCS12}
      store:    ${SSL_STORE:classpath:keystore.p12}
      password: ${SSL_PASSWORD}
      alias:    ${SSL_ALIAS}

server:
  port: ${services.port}
  servlet:
    context-path: ${services.context}
  ssl:
    enabled: ${services.security.ssl.enable}
    key-store-type: ${services.security.ssl.type}
    key-store: ${services.security.ssl.store}
    key-store-password: ${services.security.ssl.password}
    key-alias: ${services.security.ssl.alias}
spring:
  profiles:
    active: prod,doc
  datasource:
    url: jdbc:postgresql://${services.connection.database.host}/${services.connection.database.name}
    username: ${services.connection.database.user}
    password: ${services.connection.database.psw}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: account-service

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.threembank.interfaces.handler: INFO




