server:
  port: 8082
spring:
  application:
    name: '@project.artifactId@'
  profiles:
    active: dev,doc
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: config-user
      password: ${ConfigServerSecret}
      fail-fast: true

management:
  tracing:
    enabled: false