configurations:
  app:
    name: '@project.artifactId@'
    port: ${SERVER_PORT:8888}
    context: /
    profiles: ${SERV_PROFILES:dev,doc}
  connection:
    consul:
      host: 3mbank.consul.com
      port: 80
server:
  port: ${configurations.app.port}
  servlet:
    context-path: ${configurations.app.context}
spring:
  application:
    name: ${configurations.app.name}
  profiles:
    active: ${configurations.app.profiles},git,vault
  security:
    user:
      name: config-user
      password: ${ConfigServerSecret:changeit}
  cloud:
    config:
      server:
        vault:
          host: 3mbank.vault.com
          port: 8200
          scheme: http
          backend: secret
          default-key: application
          kv-version: 2
          authentication: TOKEN
          token: myroot
        git:
          uri: file:///${user.dir}
          search-paths: '/3mbank-infra/config-server-repo'
          default-label: master
          order: 2
    consul:
      host: ${configurations.connection.consul.host}
      port: ${configurations.connection.consul.port}
      discovery:
        tags: prometheus
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: health,info,vault,refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: INFO
    org.springframework.cloud.vault: DEBUG
