configurations:
  security:
    jwt:
      token:
        private-key: classpath:keys/private.key
        public-key: classpath:keys/public.pem
        expiration-at: ${JWT_EXPIRE_AT}
        expiration-rt: ${JWT_EXPIRE_RT}

server:
  port: 8081
spring:
  application:
    name: '@project.artifactId@'
  profiles:
    active: dev,doc
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: config-user
      password: ${ConfigServerSecret}
      fail-fast: true